# Generated by Django 4.2.7 on 2023-11-30 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_tag_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
